### ISSUE TITLE
자유게시판 글 쓰면 뒷페이지로 넘어감

### ISSUE THREAD

**Issue by Ddddiyong** [bjh0501/HOSEO-2B-2-FamilyToto#12]
![게시판오류](https://user-images.githubusercontent.com/10151521/63912963-7f710180-ca69-11e9-89a0-1998625e6afc.PNG)
게시판 글 작성 시 첫 페이지가 아닌 다음 페이지에 글이 나타남

**Comment by bjh0501** [comment]
해결
