### ISSUE TITLE
규원 모든페이지 테스트

### ISSUE THREAD

**Issue by bjh0501** [bjh0501/HOSEO-2B-2-FamilyToto#120]
다하면 무조건 말 ㄱㄱ

VIP테스트 하는법도 갈쳐줌

**Comment by rbdnjs0223** [comment]
이내용은 본서버 기준으로 테스트
1 충전
1.1충전내역 메일에서 회원아이디가 출력되야하는데 출력안됨

2. 대시보드
2.1 크레딧 수입경로에서 인디언포커는 undefined 로 출력

3.크레딧샵
3.1 상품 상세보기 한후 수량보다 높게 입력하면 상품수량보다 낮게 입력해달란 메시지가 출력이안되고
정상적인 경로로 접속해주세요 경고메시지 출력후 메인화면 이동됨
3.2 상품 상세보기 에서 도움말을 보면 상품 이미지랑 겹쳐서 도움말이 가려짐
3.3 크레딧샵에서 아이템 찜을 해둿는데 상세보기에선 재고가없어서 찜을 헤제를못함 (현재재고 없는아이템:원카드)
3.4 판매자가 등록한 상품을 수정할때 링크로만 이미지를 추가한 상품은 미리보기 사진 선택창이 안뜨고 최소한 한개의 이미지를 등록하라고 뜸

4.도움말
4.1 스포츠배팅 도움말이 겹침
4.2 충전페이지 도움말이 겹치고 대사가 중복 
4.3 크레딧샵 도움말에 공백하나있음

5.VIP
5.1 러시안룰렛
5.1.1 러시안룰렛 게임방 방생성자가 탈주시 그방은 게임진입 불가 
5.1.2 게임 시작도 안누르고 탈주시 시작불가
5.1.3 발사자가 탈주시 게임진행불가
5.1.4 3명기준으로 첫 탈락자가 사망시 메시지 확인을 안누르면 진행불가 (메세지는 사망자:닉네임 부분)
5.1.5 3명기준 첫사망자 이후 다음사망자 발생시 메시지 확인 안누르면 진행불가 위 5.1.4과 동일 
5.1.6 2명기준으로 방아쇠땅기기전에 상대방이 탈주시 강제패배 (자신밖에 땅길사람이 없음)

**Comment by bjh0501** [comment]
일단 1번사항 수정완료

**Comment by bjh0501** [comment]
5번빼고 전부 수정완료

**Comment by bjh0501** [comment]
5번은못고침
