### ISSUE TITLE
규원 게시판쪽 테스트하기

### ISSUE THREAD

**Issue by bjh0501** [bjh0501/HOSEO-2B-2-FamilyToto#13]
불편사항이나 버그 댓글 ㄱㄱ

**Comment by rbdnjs0223** [comment]
1. 익명유저 게시물 수정페이지에서  비밀번호 칸이 있는데 입력을 하고 수정하면 전비밀번호든 바꾼 비밀번호든 비밀번호를 틀렸다고 뜸 + 비밀번호칸에 비밀번호 입력을 안해도 게시물 수정이 됨

2.게시글을 작성하면 인터넷 서버 페이지 오류뜸 작성은 됨

3. 익명유저 댓글에 아이디 입력하면 경고창에선 4~20자 까지라고 하지만
8글자가 최대고 초과되면 메세지 미출력 및 작성안됨

4. 댓글에 답글쓰기 같은경우도 3번과 같이 8글자 초과되면 메세지에서 알수없는 에러 라고 출력 되며 작성안됨

5.게시글과 게시물 답글도 3번과 같이 아이디가 8글자 초과되면 메세지가 출력이 안되며 게시글 작성이안됨
 
6.회원 게시물 삭제시 비밀번호 입력하라는 창이 출력됨 번호 입력하든 안하든 삭제됨

7. 로그인한 계정으로 게시물 답글을 달고 자유게시판 글쓰기를하면  답글달았던 게시물에 답글이 달림 게시물을 
지워도 답글 달았던 게시물에 답글달림 
이현상은 다른 아이디로 해도 걸리는버그 
로그아웃을 하면 풀림 하지만 위현상을 다시 시도하면 위에처럼됨

8. 게시물에 이미지 등록시 이미지가 안뜸
9. 게시물에 파일 첨부시 첨부한 파일이 다운로드및 실행이 안됨
10. 게시물에 파일첨부하면 특정파일은 파일에 문제가 있습니다. 다시 업로드 해주세요. 라고 메세지출력 첨부랑 작성은 이상없이 됨

기타사항. 로그아웃이 안됨


개선사항: 댓글은 먼저쓴 기준으로오름차순으로 개선했으면 함

**Comment by bjh0501** [comment]
1번 : **익명 수정에 대해 어떻게 처리할지 안정함.** 현재는 비밀번호칸에 있는대로 수정되는듯
1. 수정할때 기존 비밀번호입력해야수정(이 경우는 비번을 수정못함)
2. 수정할때 비밀번호 입력하면 비밀번호도수정, 입력안하면 비밀번호는 수정안됨.
3. 기타 다른방법
이 3가지방법중선택ㄱ

2번 이젠 잘됨

3번, 4번, 5번 서버쪽에서 받을땐 2 ~ 8자리를 받아야하는데 프론트단에선 4 ~ 20자리로 유효성검사해서 에러가난거
- 익명글은 닉네임 몇글자부터 몇글자, 비번은 몇글자 부터 몇글자.. 등등 이런규정도 만들어야할듯
**이부분에 대해서는 입력받는 페이지들을  문서화 시킨후 나중에 일괄처리해야할듯**

6번 수정함 

7번 확인완료 
**답글하나만 달아지지않고 계단식으로 구현예정**

8번은 구현안했다고 말했어야했는데 까먹음. 지금은 리얼서버에서도  올라가짐

9번, 10번 구현안햇다고 말했어야했는데 까먹음. 지금은 파일등록은되지만 다운로드는안댐
**추후 파일 다운로드 구현예정**

로그아웃안되는 문제는 찾아봐야할듯.
_어떻게해야 안되는지 구체적으로 적기 ㄱㄱ_ (현재는 잘됨)

페이스북로그인은 갑자기 로그인안되는 버그있었는데 현재는 고침.
네이버는 검수거부나서  프로젝트아이디랑 내아이디로만 로그인가능함.

테스트서버에서는 오름차순으로 되는데 리얼서버에는 반영안한듯 현재는 됨

**Comment by bjh0501** [comment]
전부해결
