### ISSUE TITLE
로그인페이지 버튼 사이즈 문제

### ISSUE THREAD

**Issue by bjh0501** [bjh0501/HOSEO-2B-2-FamilyToto#38]
![image](https://user-images.githubusercontent.com/28896454/64559373-19e21680-d381-11e9-99a4-a7b3e67f5d5f.png)

로그인페이지버튼들을보면 통일성이 없다

로고 | 버튼이름 이런형태인데

최대한 로고 간격 맞추고 버튼이름(폰트, 자간 등등)도 통일하기

**Comment by Ddddiyong** [comment]
처리완료
