### ISSUE TITLE
09.17 게시글 테스트

### ISSUE THREAD

**Issue by rbdnjs0223** [bjh0501/HOSEO-2B-2-FamilyToto#43]
1.게시글 작성
1.1 테스트 서버에서 파일다운안됨 > 서버 에러페이지로 넘어감
1.2 테스트 서버에서 이미지올리면 깨짐
1.3 17일 15시45분 기준 리얼서버는 이상없음

2.게시글 삭제
2.1 로그인후 게시글쓰고 삭제시 서버에러 페이지로 넘어감(리얼서버랑 동일)
2.2 익명으로 글쓰고 삭제시 알수 없는 에러가 발생하였습니다. 라고 메시지가 출력된다. (리얼서버랑 동일)
2.3 아마 2.1, 2.2 에서  게시글삭제시 자유게시판으로 가야하는게 새로고침 되면서 이미 삭제된 게시글로 가서 서버에러 페이지가 뜨는거 같다.

개선사항
 댓글삭제시 삭제된댓글에 닉네임은 안남도록 했으면 함

**Comment by bjh0501** [comment]
해결완료
삭제된댓글에 닉네임이 나오도록 하는건 하상아이디어라 개선x
