### ISSUE TITLE
상품평 관련문제

### ISSUE THREAD

**Issue by bjh0501** [bjh0501/HOSEO-2B-2-FamilyToto#50]
상품을 구입한 후 상품평을 1번 달수 있음

상품평관련어떻게할건지 1,2번중에 투표 ㄱㄱ 현재는 2번으로할려함 

1. 같은상품을 여러번구입한경우 상품평여러번 달수 있는기능
2. 같은상품을 여러번 구입하더라도 상품평은 1번 달수있는기능

글고 상품평을 달경우 100~300중에 랜덤으로 마일리지 얻기기능 추가

**Comment by dlrlfgh24** [comment]
222

**Comment by Ddddiyong** [comment]
2번

**Comment by bjh0501** [comment]
과반수로 2번으로
