### ISSUE TITLE
길호 크레딧샵 테스트하기

### ISSUE THREAD

**Issue by bjh0501** [bjh0501/HOSEO-2B-2-FamilyToto#64]
테스트 해야할부분은
*즉시구매 > 상품구매페이지 > 크레딧으로구매
*즉시구매 > 상품구매페이지 > 마일리지로구매
*장바구니 > 장바구니 구매 > 크레딧으로구매
*장바구니 > 장바구니 구매 > 마일리지로구매
*각각 원스포츠아이디로 구입, 
*원스포츠아디 연동된 소셜계정으로 구입
*상품평달기 등등
--
위에서 말한거말고도 여러가지 경우의 수가 있을테니 찾아봐서 테스트ㄱㄱ
위에는 필수 테스트 사항이고 따로 테스트한건 보고ㄱㄱ 
문제점, 버그, 개선사항있으면 말 ㄱㄱ

장바구니에서 구입하는 페이지와 즉시구매하는페이지는 같게보이지만
실질적으로는 다른페이지임

 * 장바구니에서 개수변경한다음 구매하는건 현재는안됨 곧 변경예정
![image](https://user-images.githubusercontent.com/28896454/65378096-0fb00880-dcef-11e9-85f2-24d64902d0e5.png)

 * 메인에서 장바구니 누르면 기능안됨(기능 뺄지 검토중)
![image](https://user-images.githubusercontent.com/28896454/65378100-248c9c00-dcef-11e9-92b3-44075eec17e0.png)

**Comment by dlrlfgh24** [comment]
상품평 1.0이하로하면 댓글이안달아짐
900개이상사면 장바구니에안담아짐

**Comment by bjh0501** [comment]
상품평 1~5까지로 되어있엇는데 0~5까지로 수정
장바구니 개수컬럼이 tinyint로되잇엇는데 int로변경

해결완료
