### ISSUE TITLE
쇼핑몰 아이디어1

### ISSUE THREAD

**Issue by dlrlfgh24** [bjh0501/HOSEO-2B-2-FamilyToto#66]
![옵션 예제](https://user-images.githubusercontent.com/49934160/65485901-0cc73a80-dede-11e9-8ea9-fbb4a47d212d.PNG)
![옵션 예제2](https://user-images.githubusercontent.com/49934160/65485902-0cc73a80-dede-11e9-8c00-adbcfdeaa75b.PNG)
이미지처럼 특정한 상품엔 옵션같은걸 추가하는게어떰
총같은건 총알추가구입 카드는 고급카드 고급로얄카드  화투는 삐에로화투

**Comment by bjh0501** [comment]
구현안함
