### ISSUE TITLE
슬롯머신 규칙

### ISSUE THREAD

**Issue by Ddddiyong** [bjh0501/HOSEO-2B-2-FamilyToto#77]
2의 배수 2-4-6, 4-6-8 (1-3-5)(3-5-7) (1.25배)
3의 배수 3-6-9 (1.25배)

같은수 2개 배당X

7은 무조건 777만 배당O( 사람들이 배팅한 금액을 받는다. )

**Comment by bjh0501** [comment]
기존에있는 룰에서  저 룰 추가할 예정 1.25 > 1.49로

**Comment by bjh0501** [comment]
오름차순 후 아래처럼 매치되면 1.49배
0,2,4
2,4,6
4,6,8
1,3,5
3,5,7
5,7,9

해결완료
