### ISSUE TITLE
길호 상품찜 기획하기

### ISSUE THREAD

**Issue by bjh0501** [bjh0501/HOSEO-2B-2-FamilyToto#89]
![image](https://user-images.githubusercontent.com/28896454/66201579-a4970680-e6de-11e9-9116-d879b3c3ad20.png)
현재는 찜이되면 버튼이 그냥 주황색으로나오는데 이런것좀 제대로 기획좀 
글고 상품페이지도 찜버튼 어디에 넣어야할지 찜을하면 어떻게 표시될지 이런거 기획ㄱ
기능은 다구현함

**Comment by dlrlfgh24** [comment]
https://ovenapp.io/project/w02QEfdd3o8TM0BgMuzk42gStWZMNa8Q#c4ONw

**Comment by dlrlfgh24** [comment]
https://ovenapp.io/view/w02QEfdd3o8TM0BgMuzk42gStWZMNa8Q/c4ONw

**Comment by bjh0501** [comment]
기각
1. 상품페이지에서 찜누르는 버튼이없는데 어디에 넣을지 구상
2. 찜리스트  대시보드에 넣던가 장바구니에 넣던가 페이지구상ㄱㄱ 
등등 여러경우의수 생각후 다시 보고 ㄱ

**Comment by bjh0501** [comment]
완료
